# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Apr 01 20:56:51 2016
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(939, 654)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/favicon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.GetDeviceStatus = QtGui.QGroupBox(self.centralwidget)
        self.GetDeviceStatus.setTitle(_fromUtf8(""))
        self.GetDeviceStatus.setObjectName(_fromUtf8("GetDeviceStatus"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.GetDeviceStatus)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.tabWidget = QtGui.QTabWidget(self.GetDeviceStatus)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.label_online_dev_num = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_online_dev_num.setFont(font)
        self.label_online_dev_num.setTextFormat(QtCore.Qt.AutoText)
        self.label_online_dev_num.setObjectName(_fromUtf8("label_online_dev_num"))
        self.horizontalLayout_9.addWidget(self.label_online_dev_num)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        spacerItem = QtGui.QSpacerItem(168, 14, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.checkBox_osd = QtGui.QCheckBox(self.tab)
        self.checkBox_osd.setObjectName(_fromUtf8("checkBox_osd"))
        self.horizontalLayout_11.addWidget(self.checkBox_osd)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_8.addWidget(self.line)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lineEdit_devPassword = QtGui.QLineEdit(self.tab)
        self.lineEdit_devPassword.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_devPassword.setFont(font)
        self.lineEdit_devPassword.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_devPassword.setMaxLength(12)
        self.lineEdit_devPassword.setObjectName(_fromUtf8("lineEdit_devPassword"))
        self.horizontalLayout_8.addWidget(self.lineEdit_devPassword)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_10.addWidget(self.line_2)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.pushButton_clear = QtGui.QPushButton(self.tab)
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButton_clear)
        self.pushButton_refresh = QtGui.QPushButton(self.tab)
        self.pushButton_refresh.setObjectName(_fromUtf8("pushButton_refresh"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButton_refresh)
        self.horizontalLayout_10.addLayout(self.formLayout_6)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.treeWidget_devinfo = QtGui.QTreeWidget(self.tab)
        self.treeWidget_devinfo.setDragEnabled(True)
        self.treeWidget_devinfo.setAlternatingRowColors(True)
        self.treeWidget_devinfo.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidget_devinfo.setObjectName(_fromUtf8("treeWidget_devinfo"))
        self.treeWidget_devinfo.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(3, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(4, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(5, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(6, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(7, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.verticalLayout_11.addWidget(self.treeWidget_devinfo)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.Preview_frame = QtGui.QGraphicsView(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Preview_frame.setFont(font)
        self.Preview_frame.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Preview_frame.setMouseTracking(False)
        self.Preview_frame.setAutoFillBackground(False)
        self.Preview_frame.setStyleSheet(_fromUtf8("border-image: url(:/weixin/weixin_justbigger.JPG);"))
        self.Preview_frame.setObjectName(_fromUtf8("Preview_frame"))
        self.verticalLayout_12.addWidget(self.Preview_frame)
        self.checkBox_ifPreview = QtGui.QCheckBox(self.tab)
        self.checkBox_ifPreview.setObjectName(_fromUtf8("checkBox_ifPreview"))
        self.verticalLayout_12.addWidget(self.checkBox_ifPreview)
        self.line_7 = QtGui.QFrame(self.tab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_12.addWidget(self.line_7)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_ip_2 = QtGui.QLabel(self.tab)
        self.label_ip_2.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.label_ip_2.setFont(font)
        self.label_ip_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_ip_2.setWordWrap(False)
        self.label_ip_2.setObjectName(_fromUtf8("label_ip_2"))
        self.verticalLayout_10.addWidget(self.label_ip_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_ip = QtGui.QLabel(self.tab)
        self.label_ip.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ip.setFont(font)
        self.label_ip.setObjectName(_fromUtf8("label_ip"))
        self.horizontalLayout_6.addWidget(self.label_ip)
        self.lineEdit_ip = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ip.setFont(font)
        self.lineEdit_ip.setMouseTracking(True)
        self.lineEdit_ip.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_ip.setMaxLength(15)
        self.lineEdit_ip.setFrame(True)
        self.lineEdit_ip.setObjectName(_fromUtf8("lineEdit_ip"))
        self.horizontalLayout_6.addWidget(self.lineEdit_ip)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_plus = QtGui.QPushButton(self.tab)
        self.pushButton_plus.setObjectName(_fromUtf8("pushButton_plus"))
        self.horizontalLayout_7.addWidget(self.pushButton_plus)
        self.pushButton_minus = QtGui.QPushButton(self.tab)
        self.pushButton_minus.setObjectName(_fromUtf8("pushButton_minus"))
        self.horizontalLayout_7.addWidget(self.pushButton_minus)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.pushButton_ChangeIP = QtGui.QPushButton(self.tab)
        self.pushButton_ChangeIP.setObjectName(_fromUtf8("pushButton_ChangeIP"))
        self.verticalLayout_6.addWidget(self.pushButton_ChangeIP)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_12.addWidget(self.line_3)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_ip_3 = QtGui.QLabel(self.tab)
        self.label_ip_3.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.label_ip_3.setFont(font)
        self.label_ip_3.setObjectName(_fromUtf8("label_ip_3"))
        self.verticalLayout_8.addWidget(self.label_ip_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_password_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password_2.setFont(font)
        self.label_password_2.setObjectName(_fromUtf8("label_password_2"))
        self.verticalLayout_4.addWidget(self.label_password_2)
        self.label_password_3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password_3.setFont(font)
        self.label_password_3.setObjectName(_fromUtf8("label_password_3"))
        self.verticalLayout_4.addWidget(self.label_password_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit_password_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_password_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password_2.setFont(font)
        self.lineEdit_password_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_password_2.setMaxLength(32)
        self.lineEdit_password_2.setObjectName(_fromUtf8("lineEdit_password_2"))
        self.verticalLayout_3.addWidget(self.lineEdit_password_2)
        self.lineEdit_password_3 = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password_3.setFont(font)
        self.lineEdit_password_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_password_3.setMaxLength(32)
        self.lineEdit_password_3.setObjectName(_fromUtf8("lineEdit_password_3"))
        self.verticalLayout_3.addWidget(self.lineEdit_password_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.pushButton_active = QtGui.QPushButton(self.tab)
        self.pushButton_active.setObjectName(_fromUtf8("pushButton_active"))
        self.verticalLayout_5.addWidget(self.pushButton_active)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_12.addWidget(self.line_4)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_ip_4 = QtGui.QLabel(self.tab)
        self.label_ip_4.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.label_ip_4.setFont(font)
        self.label_ip_4.setObjectName(_fromUtf8("label_ip_4"))
        self.verticalLayout_9.addWidget(self.label_ip_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_password_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password_4.setFont(font)
        self.label_password_4.setObjectName(_fromUtf8("label_password_4"))
        self.horizontalLayout_3.addWidget(self.label_password_4)
        self.comboBox_osdrule = QtGui.QComboBox(self.tab)
        self.comboBox_osdrule.setObjectName(_fromUtf8("comboBox_osdrule"))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_osdrule)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_password_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password_5.setFont(font)
        self.label_password_5.setObjectName(_fromUtf8("label_password_5"))
        self.horizontalLayout_2.addWidget(self.label_password_5)
        self.lineEdit_osd = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_osd.setFont(font)
        self.lineEdit_osd.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_osd.setText(_fromUtf8(""))
        self.lineEdit_osd.setMaxLength(32)
        self.lineEdit_osd.setObjectName(_fromUtf8("lineEdit_osd"))
        self.horizontalLayout_2.addWidget(self.lineEdit_osd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton_setOsd = QtGui.QPushButton(self.tab)
        self.pushButton_setOsd.setObjectName(_fromUtf8("pushButton_setOsd"))
        self.verticalLayout_2.addWidget(self.pushButton_setOsd)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.line_5 = QtGui.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(330, 0, 16, 491))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(0, 80, 331, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 307, 56))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_localIp = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_localIp.setFont(font)
        self.lineEdit_localIp.setMouseTracking(True)
        self.lineEdit_localIp.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_localIp.setMaxLength(15)
        self.lineEdit_localIp.setFrame(True)
        self.lineEdit_localIp.setObjectName(_fromUtf8("lineEdit_localIp"))
        self.horizontalLayout.addWidget(self.lineEdit_localIp)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_getNetInfo = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_getNetInfo.setObjectName(_fromUtf8("pushButton_getNetInfo"))
        self.gridLayout.addWidget(self.pushButton_getNetInfo, 0, 0, 1, 1)
        self.pushButton_setNetInfo = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_setNetInfo.setObjectName(_fromUtf8("pushButton_setNetInfo"))
        self.gridLayout.addWidget(self.pushButton_setNetInfo, 1, 0, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout)
        self.calendarWidget = QtGui.QCalendarWidget(self.tab_2)
        self.calendarWidget.setGeometry(QtCore.QRect(50, 110, 248, 169))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.tabWidget)
        self.horizontalLayout_5.addWidget(self.GetDeviceStatus)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.treeWidget_devinfo)
        MainWindow.setTabOrder(self.treeWidget_devinfo, self.pushButton_clear)
        MainWindow.setTabOrder(self.pushButton_clear, self.pushButton_refresh)
        MainWindow.setTabOrder(self.pushButton_refresh, self.Preview_frame)
        MainWindow.setTabOrder(self.Preview_frame, self.comboBox_osdrule)
        MainWindow.setTabOrder(self.comboBox_osdrule, self.lineEdit_osd)
        MainWindow.setTabOrder(self.lineEdit_osd, self.pushButton_setOsd)
        MainWindow.setTabOrder(self.pushButton_setOsd, self.lineEdit_ip)
        MainWindow.setTabOrder(self.lineEdit_ip, self.pushButton_plus)
        MainWindow.setTabOrder(self.pushButton_plus, self.pushButton_minus)
        MainWindow.setTabOrder(self.pushButton_minus, self.lineEdit_password_2)
        MainWindow.setTabOrder(self.lineEdit_password_2, self.lineEdit_password_3)
        MainWindow.setTabOrder(self.lineEdit_password_3, self.pushButton_active)
        MainWindow.setTabOrder(self.pushButton_active, self.lineEdit_devPassword)
        MainWindow.setTabOrder(self.lineEdit_devPassword, self.lineEdit_localIp)
        MainWindow.setTabOrder(self.lineEdit_localIp, self.pushButton_getNetInfo)
        MainWindow.setTabOrder(self.pushButton_getNetInfo, self.pushButton_setNetInfo)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "搬砖工具", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "在线设备总数：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_online_dev_num.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_osd.setText(QtGui.QApplication.translate("MainWindow", "OSD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "密码：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_devPassword.setText(QtGui.QApplication.translate("MainWindow", "abcd1234", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear.setText(QtGui.QApplication.translate("MainWindow", "清除", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_refresh.setText(QtGui.QApplication.translate("MainWindow", "刷新", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.setSortingEnabled(True)
        self.treeWidget_devinfo.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "编号", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "设备型号", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "IP地址", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "OSD", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "激活", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "设备序列号", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "MAC地址", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "启动时间", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ifPreview.setText(QtGui.QApplication.translate("MainWindow", "开启预览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip_2.setText(QtGui.QApplication.translate("MainWindow", "修改网络参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip.setText(QtGui.QApplication.translate("MainWindow", "IP：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ip.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ip.setText(QtGui.QApplication.translate("MainWindow", "255.255.255.255", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>IP地址+1</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_minus.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>IP地址-1</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_minus.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_minus.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ChangeIP.setText(QtGui.QApplication.translate("MainWindow", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip_3.setText(QtGui.QApplication.translate("MainWindow", "激活设备", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password_2.setText(QtGui.QApplication.translate("MainWindow", "新密码：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password_3.setText(QtGui.QApplication.translate("MainWindow", "确认密码：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_password_2.setText(QtGui.QApplication.translate("MainWindow", "12345", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_password_3.setText(QtGui.QApplication.translate("MainWindow", "12345", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_active.setText(QtGui.QApplication.translate("MainWindow", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip_4.setText(QtGui.QApplication.translate("MainWindow", "实用功能", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password_4.setText(QtGui.QApplication.translate("MainWindow", "OSD配置：", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(0, QtGui.QApplication.translate("MainWindow", "空", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(1, QtGui.QApplication.translate("MainWindow", "IP地址末1位", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(2, QtGui.QApplication.translate("MainWindow", "IP地址末2位", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(3, QtGui.QApplication.translate("MainWindow", "完整IP地址", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password_5.setText(QtGui.QApplication.translate("MainWindow", "       +", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_setOsd.setText(QtGui.QApplication.translate("MainWindow", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Hikvision工具集", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "本地IP：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_localIp.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_localIp.setText(QtGui.QApplication.translate("MainWindow", "255.255.255.255", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_getNetInfo.setText(QtGui.QApplication.translate("MainWindow", "刷新", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_setNetInfo.setText(QtGui.QApplication.translate("MainWindow", "配置", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "实用工具", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

