# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Apr 16 19:18:13 2016
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1313, 651)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/favicon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.BMTool_frame = QtGui.QGroupBox(self.centralwidget)
        self.BMTool_frame.setTitle(_fromUtf8(""))
        self.BMTool_frame.setObjectName(_fromUtf8("BMTool_frame"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.BMTool_frame)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tabWidget = QtGui.QTabWidget(self.BMTool_frame)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.label_online_dev_num = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_online_dev_num.setFont(font)
        self.label_online_dev_num.setTextFormat(QtCore.Qt.AutoText)
        self.label_online_dev_num.setObjectName(_fromUtf8("label_online_dev_num"))
        self.horizontalLayout_9.addWidget(self.label_online_dev_num)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.pushButton_excel = QtGui.QPushButton(self.tab)
        self.pushButton_excel.setObjectName(_fromUtf8("pushButton_excel"))
        self.horizontalLayout_11.addWidget(self.pushButton_excel)
        spacerItem = QtGui.QSpacerItem(168, 14, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.checkBox_osd = QtGui.QCheckBox(self.tab)
        self.checkBox_osd.setObjectName(_fromUtf8("checkBox_osd"))
        self.horizontalLayout_11.addWidget(self.checkBox_osd)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_8.addWidget(self.line)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lineEdit_devPassword = QtGui.QLineEdit(self.tab)
        self.lineEdit_devPassword.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_devPassword.setFont(font)
        self.lineEdit_devPassword.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_devPassword.setMaxLength(12)
        self.lineEdit_devPassword.setObjectName(_fromUtf8("lineEdit_devPassword"))
        self.horizontalLayout_8.addWidget(self.lineEdit_devPassword)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_10.addWidget(self.line_2)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.pushButton_clear = QtGui.QPushButton(self.tab)
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButton_clear)
        self.pushButton_refresh = QtGui.QPushButton(self.tab)
        self.pushButton_refresh.setObjectName(_fromUtf8("pushButton_refresh"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButton_refresh)
        self.horizontalLayout_10.addLayout(self.formLayout_6)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.treeWidget_devinfo = QtGui.QTreeWidget(self.tab)
        self.treeWidget_devinfo.setDragEnabled(True)
        self.treeWidget_devinfo.setAlternatingRowColors(True)
        self.treeWidget_devinfo.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidget_devinfo.setObjectName(_fromUtf8("treeWidget_devinfo"))
        self.treeWidget_devinfo.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(2, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(3, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(4, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(5, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(6, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_devinfo.headerItem().setTextAlignment(7, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout_11.addWidget(self.treeWidget_devinfo)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.Preview_frame = QtGui.QGraphicsView(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Preview_frame.setFont(font)
        self.Preview_frame.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Preview_frame.setMouseTracking(False)
        self.Preview_frame.setAutoFillBackground(False)
        self.Preview_frame.setStyleSheet(_fromUtf8("border-image: url(:/weixin/weixin_justbigger.JPG);"))
        self.Preview_frame.setObjectName(_fromUtf8("Preview_frame"))
        self.verticalLayout_8.addWidget(self.Preview_frame)
        self.checkBox_ifPreview = QtGui.QCheckBox(self.tab)
        self.checkBox_ifPreview.setChecked(True)
        self.checkBox_ifPreview.setObjectName(_fromUtf8("checkBox_ifPreview"))
        self.verticalLayout_8.addWidget(self.checkBox_ifPreview)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.line_12 = QtGui.QFrame(self.tab)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_6.addWidget(self.line_12)
        self.label_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("ItalicT"))
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setIndent(-1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.line_7 = QtGui.QFrame(self.tab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_5.addWidget(self.line_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.line_8 = QtGui.QFrame(self.tab)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_7.addWidget(self.line_8)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_ip_2 = QtGui.QLabel(self.tab)
        self.label_ip_2.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.label_ip_2.setFont(font)
        self.label_ip_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_ip_2.setWordWrap(False)
        self.label_ip_2.setObjectName(_fromUtf8("label_ip_2"))
        self.verticalLayout_4.addWidget(self.label_ip_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_ip = QtGui.QLabel(self.tab)
        self.label_ip.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ip.setFont(font)
        self.label_ip.setObjectName(_fromUtf8("label_ip"))
        self.horizontalLayout_6.addWidget(self.label_ip)
        self.lineEdit_ip = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ip.setFont(font)
        self.lineEdit_ip.setMouseTracking(True)
        self.lineEdit_ip.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_ip.setMaxLength(15)
        self.lineEdit_ip.setFrame(True)
        self.lineEdit_ip.setObjectName(_fromUtf8("lineEdit_ip"))
        self.horizontalLayout_6.addWidget(self.lineEdit_ip)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_7.addWidget(self.line_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_ip_3 = QtGui.QLabel(self.tab)
        self.label_ip_3.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.label_ip_3.setFont(font)
        self.label_ip_3.setObjectName(_fromUtf8("label_ip_3"))
        self.verticalLayout_3.addWidget(self.label_ip_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_password_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password_2.setFont(font)
        self.label_password_2.setObjectName(_fromUtf8("label_password_2"))
        self.horizontalLayout_4.addWidget(self.label_password_2)
        self.lineEdit_password_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_password_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password_2.setFont(font)
        self.lineEdit_password_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_password_2.setMaxLength(32)
        self.lineEdit_password_2.setObjectName(_fromUtf8("lineEdit_password_2"))
        self.horizontalLayout_4.addWidget(self.lineEdit_password_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.line_9 = QtGui.QFrame(self.tab)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_7.addWidget(self.line_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_7.addWidget(self.line_4)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem1 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.line_11 = QtGui.QFrame(self.tab)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_16.addWidget(self.line_11)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_ip_4 = QtGui.QLabel(self.tab)
        self.label_ip_4.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.label_ip_4.setFont(font)
        self.label_ip_4.setObjectName(_fromUtf8("label_ip_4"))
        self.verticalLayout_2.addWidget(self.label_ip_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_password_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password_4.setFont(font)
        self.label_password_4.setObjectName(_fromUtf8("label_password_4"))
        self.horizontalLayout_3.addWidget(self.label_password_4)
        self.comboBox_osdrule = QtGui.QComboBox(self.tab)
        self.comboBox_osdrule.setObjectName(_fromUtf8("comboBox_osdrule"))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.comboBox_osdrule.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_osdrule)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_en = QtGui.QComboBox(self.tab)
        self.comboBox_en.setEnabled(True)
        self.comboBox_en.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_en.setObjectName(_fromUtf8("comboBox_en"))
        self.comboBox_en.addItem(_fromUtf8(""))
        self.comboBox_en.addItem(_fromUtf8(""))
        self.comboBox_en.addItem(_fromUtf8(""))
        self.comboBox_en.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_en)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_password_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password_5.setFont(font)
        self.label_password_5.setObjectName(_fromUtf8("label_password_5"))
        self.horizontalLayout_2.addWidget(self.label_password_5)
        self.lineEdit_osd = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_osd.setFont(font)
        self.lineEdit_osd.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_osd.setText(_fromUtf8(""))
        self.lineEdit_osd.setMaxLength(32)
        self.lineEdit_osd.setObjectName(_fromUtf8("lineEdit_osd"))
        self.horizontalLayout_2.addWidget(self.lineEdit_osd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_13 = QtGui.QFrame(self.tab)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout_2.addWidget(self.line_13)
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.line_10 = QtGui.QFrame(self.tab)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_16.addWidget(self.line_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.line_5 = QtGui.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(330, 0, 16, 491))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(0, 80, 331, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 312, 56))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_localIp = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_localIp.setFont(font)
        self.lineEdit_localIp.setMouseTracking(True)
        self.lineEdit_localIp.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_localIp.setMaxLength(15)
        self.lineEdit_localIp.setFrame(True)
        self.lineEdit_localIp.setObjectName(_fromUtf8("lineEdit_localIp"))
        self.horizontalLayout.addWidget(self.lineEdit_localIp)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_getNetInfo = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_getNetInfo.setObjectName(_fromUtf8("pushButton_getNetInfo"))
        self.gridLayout.addWidget(self.pushButton_getNetInfo, 0, 0, 1, 1)
        self.pushButton_setNetInfo = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_setNetInfo.setObjectName(_fromUtf8("pushButton_setNetInfo"))
        self.gridLayout.addWidget(self.pushButton_setNetInfo, 1, 0, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 381, 401))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.verticalLayout_12.addWidget(self.BMTool_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox_ifPreview, self.checkBox_osd)
        MainWindow.setTabOrder(self.checkBox_osd, self.pushButton_refresh)
        MainWindow.setTabOrder(self.pushButton_refresh, self.pushButton_clear)
        MainWindow.setTabOrder(self.pushButton_clear, self.lineEdit_ip)
        MainWindow.setTabOrder(self.lineEdit_ip, self.lineEdit_password_2)
        MainWindow.setTabOrder(self.lineEdit_password_2, self.comboBox_osdrule)
        MainWindow.setTabOrder(self.comboBox_osdrule, self.comboBox_en)
        MainWindow.setTabOrder(self.comboBox_en, self.lineEdit_osd)
        MainWindow.setTabOrder(self.lineEdit_osd, self.pushButton_excel)
        MainWindow.setTabOrder(self.pushButton_excel, self.treeWidget_devinfo)
        MainWindow.setTabOrder(self.treeWidget_devinfo, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.Preview_frame)
        MainWindow.setTabOrder(self.Preview_frame, self.lineEdit_devPassword)
        MainWindow.setTabOrder(self.lineEdit_devPassword, self.lineEdit_localIp)
        MainWindow.setTabOrder(self.lineEdit_localIp, self.pushButton_getNetInfo)
        MainWindow.setTabOrder(self.pushButton_getNetInfo, self.pushButton_setNetInfo)
        MainWindow.setTabOrder(self.pushButton_setNetInfo, self.textBrowser)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "搬砖工具", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "在线设备总数：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_online_dev_num.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_excel.setText(QtGui.QApplication.translate("MainWindow", "导出至Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_osd.setText(QtGui.QApplication.translate("MainWindow", "OSD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "密码：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_devPassword.setText(QtGui.QApplication.translate("MainWindow", "abcd1234", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear.setText(QtGui.QApplication.translate("MainWindow", "清除", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_refresh.setText(QtGui.QApplication.translate("MainWindow", "刷新", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.setSortingEnabled(True)
        self.treeWidget_devinfo.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "设备型号", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "IP地址", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "OSD", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "激活", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "设备序列号", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "MAC地址", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_devinfo.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "启动时间", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ifPreview.setText(QtGui.QApplication.translate("MainWindow", "开启预览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "操作：回车生效；↑↓按键改大小", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip_2.setText(QtGui.QApplication.translate("MainWindow", "修改网络参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip.setText(QtGui.QApplication.translate("MainWindow", "IP：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ip.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ip.setText(QtGui.QApplication.translate("MainWindow", "255.255.255.255", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip_3.setText(QtGui.QApplication.translate("MainWindow", "激活设备", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password_2.setText(QtGui.QApplication.translate("MainWindow", "新密码：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_password_2.setText(QtGui.QApplication.translate("MainWindow", "abcd1234", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip_4.setText(QtGui.QApplication.translate("MainWindow", "实用功能(回车生效)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password_4.setText(QtGui.QApplication.translate("MainWindow", "OSD配置：", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(0, QtGui.QApplication.translate("MainWindow", "空", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(1, QtGui.QApplication.translate("MainWindow", "IP地址末1位", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(2, QtGui.QApplication.translate("MainWindow", "IP地址末2位", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_osdrule.setItemText(3, QtGui.QApplication.translate("MainWindow", "完整IP地址", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_en.setItemText(0, QtGui.QApplication.translate("MainWindow", "空", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_en.setItemText(1, QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_en.setItemText(2, QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_en.setItemText(3, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password_5.setText(QtGui.QApplication.translate("MainWindow", "       +", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Hikvision工具集", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "本地IP：", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_localIp.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_localIp.setText(QtGui.QApplication.translate("MainWindow", "255.255.255.255", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_getNetInfo.setText(QtGui.QApplication.translate("MainWindow", "刷新", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_setNetInfo.setText(QtGui.QApplication.translate("MainWindow", "配置", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "实用工具", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">V1.0.2_Build20160412</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">代码已开源 =&gt; <span style=\" text-decoration: underline;\">https://github.com/jphome/Brickmove-Tool</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">微信关注如下公众号</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Keep in touch with me</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/weixin/weixin_justbigger.JPG\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "帮助", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

